// src/lib/data.ts

export const SALONS_DATA = [
  {
    id: 1,
    slug: "glam-studio-delhi",
    name: "Glam Studio",
    city: "Delhi",
    address: "23, Connaught Place, New Delhi",
    rating: 4.9,
    reviews: 320,
    category: "Salon & Spa",
    price: 500,
    priceLabel: "₹500 onwards",
    tags: ["Haircut", "Facial", "Spa"],
    description:
      "Glam Studio is Delhi's premium salon experience offering world-class haircuts, facials, and spa treatments in a luxurious setting.",
    images: [],
    openTime: "09:00",
    closeTime: "21:00",
    isOpen: true,
    phone: "+91 98100 00001",
    email: "glamstudio@example.com",
    services: [
      { id: 1, name: "Haircut", duration: 45, price: 500, category: "Hair" },
      { id: 2, name: "Facial", duration: 60, price: 1200, category: "Skin" },
      {
        id: 3,
        name: "Head Massage",
        duration: 30,
        price: 600,
        category: "Massage",
      },
      {
        id: 4,
        name: "Hair Color",
        duration: 90,
        price: 2000,
        category: "Hair",
      },
    ],
    staff: [
      { id: 1, name: "Ravi Kumar", role: "Senior Stylist", rating: 4.9 },
      { id: 2, name: "Sunita Devi", role: "Skin Expert", rating: 4.8 },
    ],
    testimonials: [
      {
        id: 1,
        name: "Priya S.",
        rating: 5,
        text: "Best salon in Delhi! Loved the experience.",
      },
      {
        id: 2,
        name: "Megha R.",
        rating: 5,
        text: "The facial was absolutely amazing. Will come back!",
      },
    ],
  },
  {
    id: 2,
    slug: "the-beauty-lounge-mumbai",
    name: "The Beauty Lounge",
    city: "Mumbai",
    address: "14, Bandra West, Mumbai",
    rating: 4.8,
    reviews: 210,
    category: "Makeup & Hair",
    price: 800,
    priceLabel: "₹800 onwards",
    tags: ["Makeup", "Hair Color", "Bridal"],
    description:
      "The Beauty Lounge specializes in bridal makeup and hair styling. Mumbai's go-to destination for weddings and special occasions.",
    images: [],
    openTime: "10:00",
    closeTime: "20:00",
    isOpen: true,
    phone: "+91 98200 00002",
    email: "beautylounge@example.com",
    services: [
      {
        id: 1,
        name: "Bridal Makeup",
        duration: 120,
        price: 8000,
        category: "Makeup",
      },
      {
        id: 2,
        name: "Hair Styling",
        duration: 60,
        price: 1500,
        category: "Hair",
      },
      { id: 3, name: "Nail Art", duration: 45, price: 800, category: "Nails" },
    ],
    staff: [
      { id: 1, name: "Anjali Mehta", role: "Makeup Artist", rating: 4.9 },
      { id: 2, name: "Pooja Shah", role: "Hair Stylist", rating: 4.7 },
    ],
    testimonials: [
      {
        id: 1,
        name: "Ananya M.",
        rating: 5,
        text: "Did my bridal makeup here. Absolutely stunning!",
      },
    ],
  },
  {
    id: 3,
    slug: "serenity-spa-bangalore",
    name: "Serenity Spa",
    city: "Bangalore",
    address: "8, Indiranagar, Bangalore",
    rating: 4.7,
    reviews: 180,
    category: "Spa & Massage",
    price: 1200,
    priceLabel: "₹1200 onwards",
    tags: ["Massage", "Spa", "Facial"],
    description:
      "A tranquil escape in the heart of Bangalore. Serenity Spa offers therapeutic massages and holistic wellness treatments.",
    images: [],
    openTime: "08:00",
    closeTime: "22:00",
    isOpen: true,
    phone: "+91 98300 00003",
    email: "serenityspa@example.com",
    services: [
      {
        id: 1,
        name: "Swedish Massage",
        duration: 60,
        price: 1500,
        category: "Massage",
      },
      {
        id: 2,
        name: "Deep Tissue Massage",
        duration: 90,
        price: 2200,
        category: "Massage",
      },
      {
        id: 3,
        name: "Aromatherapy",
        duration: 75,
        price: 1800,
        category: "Spa",
      },
    ],
    staff: [{ id: 1, name: "Kiran Rao", role: "Therapist", rating: 4.8 }],
    testimonials: [
      {
        id: 1,
        name: "Riya K.",
        rating: 5,
        text: "The deep tissue massage fixed my back pain. Incredible!",
      },
    ],
  },
  {
    id: 4,
    slug: "nail-republic-pune",
    name: "Nail Republic",
    city: "Pune",
    address: "5, Koregaon Park, Pune",
    rating: 4.8,
    reviews: 150,
    category: "Nail Studio",
    price: 400,
    priceLabel: "₹400 onwards",
    tags: ["Nail Art", "Manicure", "Pedicure"],
    description:
      "Pune's most loved nail studio. From classic manicures to elaborate nail art, Nail Republic does it all.",
    images: [],
    openTime: "10:00",
    closeTime: "20:00",
    isOpen: false,
    phone: "+91 98400 00004",
    email: "nailrepublic@example.com",
    services: [
      { id: 1, name: "Manicure", duration: 45, price: 400, category: "Nails" },
      { id: 2, name: "Pedicure", duration: 60, price: 600, category: "Nails" },
      { id: 3, name: "Nail Art", duration: 30, price: 300, category: "Nails" },
      {
        id: 4,
        name: "Gel Nails",
        duration: 75,
        price: 1200,
        category: "Nails",
      },
    ],
    staff: [
      { id: 1, name: "Neha Joshi", role: "Nail Technician", rating: 4.9 },
    ],
    testimonials: [
      {
        id: 1,
        name: "Sneha P.",
        rating: 5,
        text: "Best nail art in Pune. So creative and precise!",
      },
    ],
  },
  {
    id: 5,
    slug: "blush-and-bloom-hyderabad",
    name: "Blush & Bloom",
    city: "Hyderabad",
    address: "12, Jubilee Hills, Hyderabad",
    rating: 4.6,
    reviews: 130,
    category: "Bridal & Makeup",
    price: 2000,
    priceLabel: "₹2000 onwards",
    tags: ["Bridal", "Makeup", "Hair Color"],
    description:
      "Hyderabad's premier bridal studio. Blush & Bloom creates timeless looks for your most special days.",
    images: [],
    openTime: "09:00",
    closeTime: "20:00",
    isOpen: true,
    phone: "+91 98500 00005",
    email: "blushandbloom@example.com",
    services: [
      {
        id: 1,
        name: "Bridal Package",
        duration: 180,
        price: 15000,
        category: "Bridal",
      },
      {
        id: 2,
        name: "Party Makeup",
        duration: 90,
        price: 3000,
        category: "Makeup",
      },
    ],
    staff: [
      { id: 1, name: "Divya Reddy", role: "Bridal Specialist", rating: 4.8 },
    ],
    testimonials: [
      {
        id: 1,
        name: "Kavya T.",
        rating: 5,
        text: "My wedding look was absolutely perfect. Thank you!",
      },
    ],
  },
  {
    id: 6,
    slug: "urban-cuts-chennai",
    name: "Urban Cuts",
    city: "Chennai",
    address: "3, Anna Nagar, Chennai",
    rating: 4.7,
    reviews: 190,
    category: "Haircut & Color",
    price: 600,
    priceLabel: "₹600 onwards",
    tags: ["Haircut", "Hair Color", "Beard"],
    description:
      "Urban Cuts is Chennai's trendiest unisex salon. Expert stylists, modern cuts, and vibrant colors.",
    images: [],
    openTime: "09:00",
    closeTime: "21:00",
    isOpen: true,
    phone: "+91 98600 00006",
    email: "urbancuts@example.com",
    services: [
      {
        id: 1,
        name: "Men's Haircut",
        duration: 30,
        price: 600,
        category: "Hair",
      },
      {
        id: 2,
        name: "Women's Haircut",
        duration: 45,
        price: 800,
        category: "Hair",
      },
      {
        id: 3,
        name: "Beard Trim",
        duration: 20,
        price: 300,
        category: "Grooming",
      },
      {
        id: 4,
        name: "Hair Color",
        duration: 120,
        price: 2500,
        category: "Hair",
      },
    ],
    staff: [
      { id: 1, name: "Arjun Das", role: "Master Stylist", rating: 4.8 },
      { id: 2, name: "Preethi V.", role: "Colorist", rating: 4.7 },
    ],
    testimonials: [
      {
        id: 1,
        name: "Karthik M.",
        rating: 5,
        text: "Best haircut I've had in years. Highly recommend Arjun!",
      },
    ],
  },
];

export const SERVICES_DATA = [
  {
    id: 1,
    label: "Haircut",
    icon: "✂️",
    count: 420,
    description: "Precision cuts for all hair types and lengths.",
  },
  {
    id: 2,
    label: "Spa",
    icon: "🧖",
    count: 210,
    description: "Full-body relaxation and therapeutic treatments.",
  },
  {
    id: 3,
    label: "Nail Studio",
    icon: "💅",
    count: 185,
    description: "Manicures, pedicures, and creative nail art.",
  },
  {
    id: 4,
    label: "Makeup",
    icon: "💄",
    count: 160,
    description: "Party, bridal, and everyday makeup by experts.",
  },
  {
    id: 5,
    label: "Massage",
    icon: "🤲",
    count: 140,
    description: "Swedish, deep tissue, and aromatherapy massages.",
  },
  {
    id: 6,
    label: "Hair Color",
    icon: "🎨",
    count: 310,
    description: "Highlights, balayage, global color and more.",
  },
  {
    id: 7,
    label: "Facial",
    icon: "✨",
    count: 270,
    description: "Skin treatments, clean-ups, and anti-aging facials.",
  },
  {
    id: 8,
    label: "Bridal",
    icon: "👰",
    count: 95,
    description: "Complete bridal packages for your special day.",
  },
  {
    id: 9,
    label: "Beard & Grooming",
    icon: "🧔",
    count: 200,
    description: "Beard trims, shaping, and men's grooming.",
  },
  {
    id: 10,
    label: "Waxing",
    icon: "🌿",
    count: 230,
    description: "Full body and facial waxing services.",
  },
  {
    id: 11,
    label: "Keratin",
    icon: "💆",
    count: 120,
    description: "Smoothening and straightening treatments.",
  },
  {
    id: 12,
    label: "Pedicure",
    icon: "🦶",
    count: 175,
    description: "Foot care, scrubs, and relaxing pedicures.",
  },
];

export const CITIES_DATA = [
  { id: 1, name: "Delhi", salons: 120, color: "from-orange-400 to-rose-500" },
  { id: 2, name: "Mumbai", salons: 95, color: "from-blue-400 to-indigo-500" },
  { id: 3, name: "Bangalore", salons: 80, color: "from-green-400 to-teal-500" },
  {
    id: 4,
    name: "Hyderabad",
    salons: 60,
    color: "from-purple-400 to-pink-500",
  },
  { id: 5, name: "Pune", salons: 55, color: "from-amber-400 to-orange-500" },
  { id: 6, name: "Chennai", salons: 50, color: "from-cyan-400 to-blue-500" },
  { id: 7, name: "Kolkata", salons: 45, color: "from-rose-400 to-red-500" },
  {
    id: 8,
    name: "Ahmedabad",
    salons: 38,
    color: "from-yellow-400 to-amber-500",
  },
];
